[platformio]
default_envs = lilygo_t5_47_s3

[env:lilygo_t5_47_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.arduino.memory_type = qio_opi

lib_deps =
  adafruit/Adafruit BME280 Library @ ^2.3.0
  adafruit/Adafruit Unified Sensor @ ^1.1.15
  https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#esp32s3
  bblanchon/ArduinoJson @ ^6.21.5

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1
  -DLOG_LOCAL_LEVEL=ESP_LOG_INFO
