[platformio]
default_envs = d1_mini_pro

[env:d1_mini_pro]
platform = espressif8266
board = d1_mini_pro
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
  adafruit/Adafruit BME280 Library @ ^2.3.0
  adafruit/Adafruit Unified Sensor @ ^1.1.15
  https://github.com/mcauser/Adafruit_SSD1306.git#esp8266-64x48
  adafruit/Adafruit GFX Library @ ^1.11.10
  bblanchon/ArduinoJson @ ^6.21.5
